### ISSUE TITLE
проблемы и вопросы

### ISSUE THREAD

**Issue by linerdom** [tarampampam/wget-gui-light#15]
Приветствую.
1. на каждую закачку выпадает менюшка 
Task "http://..." return message
Task PID not valid
но при этом закачивает

2. как назначить папку для скачивания? 

3. Не качает документы с вконтакта и Я.Диска, сообщает
Task "https://yadi.sk/i/KeuWXTMCebt5J" return message
Task completed too fast (probably with error)

**Comment by tarampampam** [comment]
1. Заряда манны не хватает чтоб прочитать ваши конфиги и логи.
2. Прочитать документацию.
3. И не должен качать.
