### ISSUE TITLE
Закачка с файлообменников

### ISSUE THREAD

**Issue by mr-butch** [tarampampam/wget-gui-light#21]
Возможно ли реализовать закачку с популярных файлообменников (бесплатный режим) в ручном режиме?
То есть пройдя по ссылке в браузере -> выждать время -> ввести код проверки и на последнем этапе скопировать ссылку и вставить в скрипт. 
В текущей версии работает в Nitroflare.com, но не работает в TurboBit.net, HitFile.net...

**Comment by tarampampam** [comment]
Нет, к сожалению, в ближайшее время не будет реализовано по причине отсутствия времени
